# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Eamonmca.github.io/nbdev_demo/"

git_url = "https://github.com/Eamonmca/nbdev_demo/tree/master/"

def custom_doc_links(name): return None
